name: Deploy to Heroku

on:
  push:
    branches:
      - master  # Cambia esto a la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Cambia esto a la versión de Python que estás usando

      - name: Upgrade setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt  # Apunta al archivo dentro de src

      - name: Run tests
        run: |
          python src/manage.py test  # Asegúrate de que apunte correctamente a manage.py dentro de src

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a <nombre-de-tu-app-heroku>
          git push heroku main
